services:
  traefik:
    image: traefik:v3.5
    command:
      - "--api.insecure=true"        # Aktivera Traefiks dashboard (ej för produktion)
      - "--providers.docker=true"    # Läs labels från Docker
      - "--entrypoints.web.address=:80" # Entrypoint på port 80
    ports:
      - "80:80"
      - "8080:8080"                  # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: containous/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
